version: "3.9"

services:
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    # install deps, then start the server
    command: ["sh", "-c", "npm install && node server.js"]
    expose:
      - "3333"
    ports:
      - "3333:3333"

  firewall:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend
